import { ActiveScreen as AS, Screens } from "screens/screens.slint";
import { ActiveColors as AC } from "properties/colors.slint";
import { StartGGState as SGGState } from "properties/start_gg_state.slint";
import { ComboBox, Button } from "std-widgets.slint";

import { MainScreen } from "screens/main_screen/main_screen.slint";
import { OAuthStep } from "screens/main_screen/oauth_panel.slint";
import { PlayerDataScreen } from "screens/player_data_screen.slint";

import { TournamentsListScreen } from "screens/tournaments_list/tournaments_list.slint";

import { InitializationErrorWindow } from "initialization_window.slint";

export component EZPRWindow inherits Window {

    in-out property <string> oauth-hyperlink-url;
    in-out property <OAuthStep> oauth-step: WEBSERVER-UP;

    min-height: 640px;
    min-width: 800px;

    callback oauth_start_auth_button_clicked();
    callback oauth_hyperlink_clicked();
    callback oauth_cancel_button_clicked();
    callback oauth_close_button_clicked();

    title: "EZPR - The Easy Power Rankings Tool!";

    if(AS.screen == Screens.MAIN): MainScreen {
        width: 100%;
        height: 100%;
        oauth-step: oauth-step;

        hyperlink-url: oauth-hyperlink-url;

        oauth_start_auth_button_clicked => {
            oauth_start_auth_button_clicked();
        }
        oauth_hyperlink_clicked => {
            oauth_hyperlink_clicked();
        }
        oauth_cancel_button_clicked => {
            oauth_cancel_button_clicked();
        }
        oauth_close_button_clicked => {
            oauth_close_button_clicked();
        }
    }

    if(AS.screen == Screens.PLAYERDATA): PlayerDataScreen {
        width: 100%;
        height: 100%;
    }

    if(AS.screen == Screens.TOURNAMENT-LIST): TournamentsListScreen {
        width: 100%;
        height: 100%;
    }
}

export {
    AS as ActiveScreen,
    AC as ActiveColors,
    SGGState as StartGGState,

    InitializationErrorWindow,
}
