import { ActiveScreen as AS, Screens } from "screens/screens.slint";
import { ActiveColors as AC } from "properties/colors.slint";
import { ComboBox, Button } from "std-widgets.slint";

import { MainScreen } from "screens/main_screen/main_screen.slint";
import { PlayerDataScreen } from "screens/player_data_screen.slint";

export component EZPRWindow inherits Window {

    min-height: 640px;
    min-width: 800px;

    callback oauth_signin_button_clicked();
    callback oauth_cancel_button_clicked();
    callback oauth_close_button_clicked();

    title: "EZPR - The Easy Power Rankings Tool!";

    if(AS.screen == Screens.MAIN): MainScreen {
        width: 100%;
        height: 100%;

        oauth_signin_button_clicked => { oauth_signin_button_clicked(); }
        oauth_cancel_button_clicked => { oauth_cancel_button_clicked(); }
        oauth_close_button_clicked => { oauth_close_button_clicked(); }
    }

    if(AS.screen == Screens.PLAYERDATA): PlayerDataScreen {
        width: 100%;
        height: 100%;
    }
}