export component EZPRButton {
    in-out property <color> background: white;
    in-out property <string> text <=> txt.text;
    in-out property <color> color: black;
    in-out property <length> font-size <=> txt.font-size;

    in-out property <bool> enabled: true;

    in-out property <length> border-width <=> rect.border-width;
    in-out property <brush> border-color <=> rect.border-color;
    in-out property <length> border-radius <=> rect.border-radius;
    
    callback clicked <=> ta.clicked;

    in-out property <length> button-padding: 15px;

    rect := Rectangle {
        min-width: txt.width + button-padding;
        min-height: txt.height + button-padding;

        border-width: 1px;
        border-color: black;
        border-radius: 5px;

        padding: 15px;

        animate background {
            duration: 50ms;
            easing: ease-out;
        }

        states [
            nofocus when !enabled: {
                background: root.background;
            }

            standard when !ta.has-hover: {
                background: root.background;
            }

            clicked when ta.pressed: {
                background: root.background.darker(35%);
            }

            hovered when ta.has-hover: {
                background: root.background.darker(25%);
            }
        ]

        ta := TouchArea {
            width: 100%;
            height: 100%;
            enabled: enabled;
        }

        txt := Text {
            color: color;
        }
    }
}

export component ClickableText inherits Rectangle {

    in-out property <string> text <=> txt.text;
    in-out property <color> text-color: black;
    in-out property <color> underline-color: blue;
    in-out property <color> background-color: white;
    callback clicked <=> ta.clicked;

    animate background {
        duration: 50ms;
        easing: ease-out;
    }

    states [
        normal when !ta.has-hover: {
            background: background-color;
        }

        pressed when ta.pressed: {
            background: background-color.darker(35%);
        }
        
        hover when ta.has-hover: {
            background: background-color.darker(25%);
        }
    ]

    ta := TouchArea {
        height: 100%;
        width: 100%;
    }

    txt := Text {
        width: 100%;
        color: text-color;
        wrap: TextWrap.word-wrap;

        Rectangle {
            y: parent.height + 2px;
            width: ta.has-hover ? 90% : 0%;
            animate width {
                duration: 100ms;
                easing: ease-in-out-expo;
            }
            height: 2px;
            background: underline-color;
        }
    }
}

export component Hyperlink inherits Text {

    callback clicked <=> ta.clicked;

    color: blue;

    ta := TouchArea {
        height: 100%;
        width: 100%;
        mouse-cursor: pointer;
    }
}