import { Button } from "std-widgets.slint";
import { ActiveColors as AC } from "../../properties/colors.slint";
import { ActiveScreen as AS, Screens } from "../screens.slint";
import { OAuthPanel } from "oauth_panel.slint";

import { EZPRButton } from "../../components.slint";

export component MainScreen {
    in-out property <string> hyperlink-url;
    callback get_oauth_hyperlink() -> string;

    callback oauth_signin_button_clicked();
    callback oauth_cancel_button_clicked();
    callback oauth_close_button_clicked();

    callback second_button_clicked();

    Rectangle {
        background: #327cc7;

        VerticalLayout {

            alignment: start;

            Text {
                font-size: 48px;
                font-weight: 800;
                color: black;
                horizontal-alignment: center;

                text: "EZPR - The Easy PR Tool";
            }

            HorizontalLayout {
                padding: 50px;
                alignment: space-around;
                
                EZPRButton {
                    text: "Create New Season";
                    background: gray;
                    color: white;
                    font-size: 16px;

                    clicked => {
                        AS.screen = Screens.PLAYERDATA;
                    }
                }

                EZPRButton {
                    text: "Load Existing Season";
                    background: gray;
                    color: white;
                    font-size: 16px;
                }
            }

            EZPRButton {
                text: "Connect Start.GG Account (OAUTH2)";
                clicked => {
                    oauth_popup.show();
                }
            }
        }

        oauth_popup := PopupWindow {

            x: (parent.width - 400px) / 2;
            y: (parent.height - 400px) / 2;

            close-policy: no-auto-close;
            width: 400px;
            height: 400px;

            OAuthPanel {
                oauth_signin_button_clicked => { oauth_signin_button_clicked(); }
                oauth_cancel_button_clicked => { oauth_cancel_button_clicked(); }

                oauth_close_button_clicked => {
                    oauth_close_button_clicked();
                    oauth_popup.close();
                }
            }
        }
    }
}