import { Button } from "std-widgets.slint";
import { ActiveColors as AC } from "../../properties/colors.slint";
import { ActiveScreen as AS, Screens } from "../screens.slint";
import { OAuthPanel, OAuthStep } from "oauth_panel.slint";

import { EZPRButton } from "../../components.slint";

export component MainScreen {
    in-out property <string> hyperlink-url;
    in-out property <bool> oauth-visible: false;
    in-out property <OAuthStep> oauth-step;

    callback oauth_start_auth_button_clicked();
    callback oauth_hyperlink_clicked();
    callback oauth_cancel_button_clicked();
    callback oauth_close_button_clicked();

    callback second_button_clicked();

    Rectangle {
        background: #327cc7;

        VerticalLayout {

            alignment: start;

            Text {
                font-size: 48px;
                font-weight: 800;
                color: black;
                horizontal-alignment: center;

                text: "EZPR - The Easy PR Tool";
            }

            HorizontalLayout {
                padding: 50px;
                alignment: space-around;
                
                EZPRButton {
                    text: "Create New Season";
                    enabled: !oauth-visible;
                    background: gray;
                    color: white;
                    font-size: 16px;

                    clicked => {
                        AS.screen = Screens.PLAYERDATA;
                    }
                }

                EZPRButton {
                    text: "Load Existing Season";
                    enabled: !oauth-visible;
                    background: gray;
                    color: white;
                    font-size: 16px;
                }
            }

            EZPRButton {
                enabled: !oauth-visible;
                text: "Connect Start.GG Account (OAUTH2)";
                clicked => {
                    oauth_start_auth_button_clicked();
                    oauth-visible = true;
                }
            }
        }

        if oauth-visible: OAuthPanel {

            height: 400px;
            width: 400px;
            oauth-step: oauth-step;

            oauth_hyperlink_clicked => {
                oauth_hyperlink_clicked();
            }
            
            oauth_cancel_button_clicked => {
                oauth_cancel_button_clicked();
                oauth-visible = false;
            }

            oauth_close_button_clicked => {
                oauth_close_button_clicked();
                oauth-visible = false;
            }
        }
    }
}