import { Button } from "std-widgets.slint";
import { ActiveColors as AC } from "../../properties/colors.slint";
import { ActiveScreen as AS, Screens } from "../screens.slint";
import { OAuthPanel } from "oauth_panel.slint";

import { EZPRButton } from "../../components.slint";

export component MainScreen {
    in-out property <string> hyperlink-url;
    in-out property <bool> oauth-visible: false;

    callback oauth_start_auth_button_clicked();
    callback oauth_hyperlink_clicked();
    callback oauth_cancel_button_clicked();
    callback oauth_close_button_clicked();

    callback second_button_clicked();

    Rectangle {
        background: #327cc7;

        VerticalLayout {

            alignment: start;

            Text {
                font-size: 48px;
                font-weight: 800;
                color: black;
                horizontal-alignment: center;

                text: "EZPR - The Easy PR Tool";
            }

            HorizontalLayout {
                padding: 50px;
                alignment: space-around;
                
                EZPRButton {
                    text: "Create New Season";
                    enabled: !oauth-visible;
                    background: gray;
                    color: white;
                    font-size: 16px;

                    clicked => {
                        AS.screen = Screens.PLAYERDATA;
                    }
                }

                EZPRButton {
                    text: "Load Existing Season";
                    enabled: !oauth-visible;
                    background: gray;
                    color: white;
                    font-size: 16px;
                }
            }

            EZPRButton {
                enabled: !oauth-visible;
                text: "Connect Start.GG Account (OAUTH2)";
                clicked => {
                    oauth_start_auth_button_clicked();
                    // oauth_popup.show();
                    oauth-visible = true;
                }
            }
        }

        // oauth_popup := PopupWindow {

        //     x: (parent.width - 400px) / 2;
        //     y: (parent.height - 400px) / 2;

        //     close-policy: no-auto-close;
        //     width: 400px;
        //     height: 400px;

            if oauth-visible: OAuthPanel {

                height: 400px;
                width: 400px;
                z: 10;

                oauth_hyperlink_clicked => {
                    oauth_hyperlink_clicked();
                }
                
                oauth_cancel_button_clicked => {
                    oauth_cancel_button_clicked();
                    // oauth_popup.close();
                    oauth-visible = false;
                }

                oauth_close_button_clicked => {
                    oauth_close_button_clicked();
                    // oauth_popup.close();
                    oauth-visible = false;
                }
            }
        // }
    }
}