import { Spinner, ProgressIndicator, Button } from "std-widgets.slint";
import { Hyperlink, EZPRButton } from "../../components.slint";
import { ActiveColors as AC } from "../../properties/colors.slint";
import { StartGGState as SGGState } from "../../properties/start_gg_state.slint";
import { ActiveColors as AC } from "../../properties/colors.slint";

export enum OAuthStep {
    WEBSERVER_UP,
    CODE_OBTAINED,
}

export component OAuthPanel inherits Rectangle {

    width: 400px;
    height: 400px;
    background: white;
    border-color: black;
    border-width: 2px;
    border-radius: 5px;

    callback oauth_hyperlink_clicked();
    callback oauth_cancel_button_clicked();
    callback oauth_close_button_clicked();
    // code get actions will be rust-side

    in-out property <OAuthStep> oauth-step: WEBSERVER-UP;

    VerticalLayout {
        alignment: center;
        spacing: 40px;
        padding: 20px;

        if oauth-step == OAuthStep.WEBSERVER-UP: Rectangle {
            height: 70%;
            
            VerticalLayout {
                height: 100%;
                
                Text {
                    font-weight: 1000;
                    font-size: 18px;
                    color: AC.text;
                    horizontal-alignment: center;
                    text: "Sign in to Start.GG";
                }

                Text {
                    width: 100%;
                    wrap: TextWrap.word-wrap;
                    color: AC.text;
                    text: "Start.GG access is needed to query data from Start.GG's API, so to continue, please sign in with your Start.GG account.";
                    font-weight: 600;
                }

                HorizontalLayout {
                    width: 100%;
                    alignment: start;
                    spacing: 0px;

                    Text {
                        color: AC.text;
                        text: "1) Please click ";
                        font-weight: 600;
                    }

                    Hyperlink {
                        text: "here";
                        font-weight: 600;
                        clicked => {
                            oauth_hyperlink_clicked();
                        }
                    }

                    Text {
                        color: AC.text;
                        font-weight: 600;
                        text: " to sign in to your Start.GG Account.";
                    }
                }

                Text {
                    color: AC.text;
                    font-weight: 600;
                    text: "2) Click the \"Allow\" button on the webpage that opens.";
                }

                Text {
                    width: 100%;
                    wrap: TextWrap.word-wrap;
                    color: AC.text;
                    font-weight: 600;
                    text: "This page will update automatically once these steps are taken...";
                }

                Spinner {
                    width: 100%;
                    height: 100px;
                    indeterminate: true;
                }
            }
        }

        if oauth-step == OAuthStep.CODE-OBTAINED: Rectangle {
            height: 70%;

            VerticalLayout {
                height: 100%;
                
                Text {
                    font-weight: 1000;
                    font-size: 18px;
                    color: AC.text;
                    horizontal-alignment: center;
                    text: "Sign in Complete!";
                }

                Text {
                    horizontal-alignment: center;
                    width: 100%;
                    wrap: TextWrap.word-wrap;
                    font-weight: 600;
                    color: AC.text;
                    text: "Thank you for signing in, \{SGGState.startgg-user}! This popup may now be closed.";
                }
            }
        }

        if oauth-step == OAuthStep.WEBSERVER-UP: EZPRButton {
            text: "Cancel";
            clicked => { oauth_cancel_button_clicked(); }
        }

        if oauth-step == OAuthStep.CODE-OBTAINED: EZPRButton {
            text: "Close";
            clicked => { oauth_close_button_clicked(); }
        }
    }

}